name: Generate snake animation

on:
  workflow_dispatch:   # Only runs when you manually trigger it from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Abhay030405
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload snake.svg as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/


